### ISSUE TITLE
Clean Up Sprint 2

### ISSUE THREAD

**Issue by Patertuck** [sopra-fs24-group-26/server#187]
- [x] sopra-fs24-group-26/client#142
- [x] sopra-fs24-group-26/client#150
- [x] sopra-fs24-group-26/server#194
- [x] sopra-fs24-group-26/client#143
- [x] sopra-fs24-group-26/client#144
- [x] sopra-fs24-group-26/client#145
