### ISSUE TITLE
User Story 02: As a website user, I want to be able to join a room that another user has created in order to join my friends/other players in a game.

### ISSUE THREAD

**Issue by Twhining** [sopra-fs24-group-26/server#2]
- [x] sopra-fs24-group-26/client#52
- [x] sopra-fs24-group-26/client#51
- [x] sopra-fs24-group-26/client#40
- [x] sopra-fs24-group-26/client#2
- [x] sopra-fs24-group-26/server#106 
- [x] sopra-fs24-group-26/client#66
