### ISSUE TITLE
User Story 03: As a website user, when the lobby owners starts the game all players get transferred to a game screen in order to begin playing the game.

### ISSUE THREAD

**Issue by Twhining** [sopra-fs24-group-26/server#3]
- [x] sopra-fs24-group-26/client#47
- [x] sopra-fs24-group-26/server#94
- [x] sopra-fs24-group-26/client#54
- [x] sopra-fs24-group-26/client#55
- [x] sopra-fs24-group-26/client#56
- [x] sopra-fs24-group-26/server#129
- [x] sopra-fs24-group-26/client#63
- [x] sopra-fs24-group-26/client#77
- [x] sopra-fs24-group-26/client#85
- [x] sopra-fs24-group-26/client#74
- [x] sopra-fs24-group-26/client#75
- [x] sopra-fs24-group-26/server#122
- [x] sopra-fs24-group-26/client#84
- [x] sopra-fs24-group-26/client#97
