### ISSUE TITLE
User Story 04: As a player in the game, when I own a path, on my turn I want to be able to dig it into the map at the position of my choice in order to take a specific direction on the map.

### ISSUE THREAD

**Issue by Twhining** [sopra-fs24-group-26/server#4]
- [x] sopra-fs24-group-26/client#7
- [x] sopra-fs24-group-26/client#6
- [x] sopra-fs24-group-26/client#8
- [x] sopra-fs24-group-26/server/issues/128
- [x] sopra-fs24-group-26/client#96
