### ISSUE TITLE
Initial Logic and System Architecture

### ISSUE THREAD

**Issue by Patertuck** [sopra-fs24-group-26/server#53]
- [x] sopra-fs24-group-26/client#25
- [x] sopra-fs24-group-26/client#26
- [x] sopra-fs24-group-26/server#56
- [x] sopra-fs24-group-26/server#57
- [x] sopra-fs24-group-26/server#58
- [x] sopra-fs24-group-26/server#59
