### ISSUE TITLE
Clean up Github repository

### ISSUE THREAD

**Issue by Patertuck** [sopra-fs24-group-26/server#66]
- [x] sopra-fs24-group-26/server#67
- [x] sopra-fs24-group-26/client#33
- [x] sopra-fs24-group-26/server#70
- [x] sopra-fs24-group-26/client#94
- [x] #173
- [x] sopra-fs24-group-26/server#142
- [x] sopra-fs24-group-26/client#98
