### ISSUE TITLE
User Story 14: As a player, when all players join the game they get a finished setup game in order for them to start playing the game

### ISSUE THREAD

**Issue by Patertuck** [sopra-fs24-group-26/server#98]
- [ ] sopra-fs24-group-26/client#57
- [ ] sopra-fs24-group-26/client#3
- [ ] sopra-fs24-group-26/client#41
- [ ] sopra-fs24-group-26/client#42
