### ISSUE TITLE
User Story 16: As a player, when I am in the titlescreen/lobby or in the game, I want to have beautiful game art to enhance my experience

### ISSUE THREAD

**Issue by Patertuck** [sopra-fs24-group-26/server#99]
- [x] sopra-fs24-group-26/client#59
- [x] sopra-fs24-group-26/client#68
- [x] sopra-fs24-group-26/client#69
- [x] sopra-fs24-group-26/client#70
- [x] sopra-fs24-group-26/client#71
- [x] sopra-fs24-group-26/client#72
- [x] sopra-fs24-group-26/client#99
- [x] sopra-fs24-group-26/client#91
- [x] sopra-fs24-group-26/client#114
- [x] sopra-fs24-group-26/client#115
- [x] sopra-fs24-group-26/client#146
